class X2StrategyElement_FacilityUpgrade_AWC_Custom extends X2StrategyElement_DefaultFacilityUpgrades;

static function array<X2DataTemplate> CreateTemplates()
{
	local array<X2DataTemplate> Upgrades;

	// Infirmary
	Upgrades.AddItem(CreateInfirmary_GeneModChamberTemplate());

	return Upgrades;
}

//---------------------------------------------------------------------------------------
// INFIRMARY UPGRADES
//---------------------------------------------------------------------------------------
static function X2DataTemplate CreateInfirmary_GeneModChamberTemplate()
{
	local X2FacilityUpgradeTemplate Template;
	local ArtifactCost Resources;

	`CREATE_X2TEMPLATE(class'X2FacilityUpgradeTemplate', Template, 'Infirmary_GeneModdingChamber');
	Template.PointsToComplete = 0;
	Template.MaxBuild = 1;
//BEGIN AUTOGENERATED CODE: Template Overrides 'Infirmary_RecoveryChamber'
	Template.strImage = "img:///UILibrary_XPACK_StrategyImages.ChooseFacility_Infirmary_Hypervital_Module";
//END AUTOGENERATED CODE: Template Overrides 'Infirmary_RecoveryChamber'
	Template.OnUpgradeAddedFn = OnUpgradeAdded_UnlockStaffSlot;

	// Stats
	Template.iPower = -2;
	Template.UpkeepCost = 25;

	// Cost
	Resources.ItemTemplateName = 'Supplies';
	Resources.Quantity = 80;
	Template.Cost.ResourceCosts.AddItem(Resources);

	return Template;
}